# Generated by Django 4.1 on 2022-09-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='contentId',
            field=models.IntegerField(default=1234),
        ),
    ]
